### ISSUE TITLE
Connection issue

### ISSUE THREAD

**Issue by dmdukr** [JH-Soft-Technology/InelsForHass#13]
Thank you for your addon, it will make life a lot easier for all Inels users.
I'm having trouble connecting. I don't understand what I'm doing wrong. 
My Inels system is built in the classic way - Devices - Inels Bus - Connection Server.
When I enter data for Connection Server I've got  an error "Unexpected error".
As IP I entered just numbers, as port - 8001, as name is arbitrary. On this IP responds web interface of Connection Server on port 8080.
Log attached. 
Configuration file in the inels folder is not found.

Logger: custom_components.inels.config_flow
Source: custom_components/inels/config_flow.py:49
Integration: Inels (documentation)
First occurred: 20:15:41 (1 occurrences)
Last logged: 20:15:41

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/inels/config_flow.py", line 75, in async_step_user
    info = await validate_input(self.hass, user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/inels/config_flow.py", line 49, in validate_input
    ping = await hass.async_add_executor_job(api.ping)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyinels/api/__init__.py", line 79, in ping
    return self.proxy.ping()
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/xmlrpc/client.py", line 1122, in __call__
    return self.__send(self.__name, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/xmlrpc/client.py", line 1464, in __request
    response = self.__transport.request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/xmlrpc/client.py", line 1166, in request
    return self.single_request(host, handler, request_body, verbose)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/xmlrpc/client.py", line 1178, in single_request
    http_conn = self.send_request(host, handler, request_body, verbose)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/xmlrpc/client.py", line 1291, in send_request
    self.send_content(connection, request_body)
  File "/usr/local/lib/python3.11/xmlrpc/client.py", line 1321, in send_content
    connection.endheaders(request_body)
  File "/usr/local/lib/python3.11/http/client.py", line 1281, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1041, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.11/http/client.py", line 979, in send
    self.connect()
  File "/usr/local/lib/python3.11/http/client.py", line 945, in connect
    self.sock = self._create_connection(
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/socket.py", line 851, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.11/socket.py", line 836, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

========================================================
Logger: custom_components.inels.config_flow
Source: custom_components/inels/config_flow.py:49
Integration: Inels (documentation)
First occurred: 16:13:36 (3 occurrences)
Last logged: 20:16:03

Unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pyinels/api/__init__.py", line 69, in __conn
    con = ServerProxy(self.__host + ":" + str(self.__port))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/xmlrpc/client.py", line 1432, in __init__
    raise OSError("unsupported XML-RPC protocol")
OSError: unsupported XML-RPC protocol

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/inels/config_flow.py", line 75, in async_step_user
    info = await validate_input(self.hass, user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/inels/config_flow.py", line 49, in validate_input
    ping = await hass.async_add_executor_job(api.ping)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyinels/api/__init__.py", line 79, in ping
    return self.proxy.ping()
           ^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyinels/api/__init__.py", line 51, in proxy
    self.__proxy = self.__conn()
                   ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyinels/api/__init__.py", line 74, in __conn
    raise ApiException(
pyinels.exception.ApiException: ('common_exception', 'Exception occur', OSError('unsupported XML-RPC protocol'))

**Comment by jhoralek** [comment]
Hi there,

use ```http://IP_ADDRESS``` instead of IP address only.


Kind regards

J.H.

**Comment by dmdukr** [comment]
Thank you a lot

**Comment by jhoralek** [comment]
It's not very well explained.

In the future, I'll add some explanation for each input for better clarification.

Closing this issue
