### ISSUE TITLE
Configuration help

### ISSUE THREAD

**Issue by hanyzzz82** [JH-Soft-Technology/InelsForHass#14]
Hello, thank you for this integration!

May I kindly ask you to provide me with more details about the configuration?

Service url? - is it url of the Inels CPU or IMM?

Is it compatible with Inels 2nd generation?

Thanks a lot
Jan Fiala

**Comment by jhoralek** [comment]
Sorry for late respons,

I didn't came accross this project since last update.

IMM whole url has to be provided. ```http://ip_address``` 

CU2 may or may not work. It depends. 

I think lights and switches should work. Try it and you'll see. 

If some error will rice, then do not hesitate to contact me. We can solve it together.

Kind regards

JH.

**Comment by hanyzzz82** [comment]
Hi, thanks for your answer.

If it communicates thru the connection server and not directly with CU, then I suppose it should work also with Inels Gen2. The connection server is identical for Inels 2 and 3. 

I tried to setup a connection, but when I start InelsForHass, a  window with 3 fields without any descriptions appears.

I suppose the first one is for IMM url in format http://ip_address and the two 
![inelshass](https://github.com/JH-Soft-Technology/InelsForHass/assets/102258216/317bd071-af12-4f18-bccf-d434c8a73a4a)
next fields? port, credentials...? 

I tried various combination but without success..

Thanks in advance ;-)
Regards
JF

**Comment by jhoralek** [comment]
First is url of connection server, second is port 8001 and the last one does nothing.

 You can put string CU2 or whatever you want.

The last one should have been to recognize the CU unit type, but it is not implemented now.

Kind regards

JH

**Comment by hanyzzz82** [comment]
Thanks for the hint!
Now I am able to access the IMM, see the entities nevertheless all of them are unavailable. 
IMM is up and running, I havent noticed any fruther setting options in Hass integration so I suppose it might be caused by the old 2nd gen INELS. 
Or any other idea?

**Comment by jhoralek** [comment]
Any HA log?

**Comment by hanyzzz82** [comment]
[home-assistant_inels_2024-01-08T18-40-24.918Z.log](https://github.com/JH-Soft-Technology/InelsForHass/files/13865125/home-assistant_inels_2024-01-08T18-40-24.918Z.log)

**Comment by jhoralek** [comment]
I found error wit some kind of entity which causes problems. 

Do you have any unix system in your local network?

I'll prepare python script which will get all raw data from your CU unit. After that, I'll debug it and correct integration to avoid this issue.

What I need from you is local IP address of your IMM. I need to use it in that script.


But not today, Mandalorian is waiting.✌️

Kind regards

JH

**Comment by hanyzzz82** [comment]
Of course, no stress. :-)
I am not aware of any UNIX system in my local network.
IMM IP: 192.168.88.115

thx JF


po 8. 1. 2024 v 20:08 odesílatel Jiří Horálek ***@***.***>
napsal:

**Comment by hanyzzz82** [comment]
Hi, is there any chance to investigate the errors in the near future? 

Thanks a lot for your feedback ;-)

JF

**Comment by jhoralek** [comment]
sorry for late response.

Here is a setup what to do to get raw data with all of your devices.

https://github.com/JH-Soft-Technology/pyinels/issues/27#issuecomment-1576908385

**Comment by hanyzzz82** [comment]
Hi, thanks for your reply.

As Im not an advanced user in programming, do I understand well I need
to go thru the following steps:

1. I run this script in HA and save it as devices.py

from pyinels.api import Api
from unittest import TestCase

api = Api("http://IP_ADDRESS_OF_CONNECTION_SERVER", 8001, "CU3")
rooms = api.getRooms()

with open('raw_data.txt', 'w',encoding='utf-8') as f:
    for room in rooms:
        devices = api.getRoomDevicesRaw(room)
        f.write(devices)
        f.write('\n')

2. in next step I need to update the __init__.py as described in
https://github.com/JH-Soft-Technology/pyinels/pull/28

By the way, I use integration InelsForHass, not Pyinels. Is there any
difference between them?

I'm sorry for stupid questions.


čt 22. 2. 2024 v 14:19 odesílatel Jiří Horálek
***@***.***> napsal:

**Comment by jhoralek** [comment]
Hi hanyzzz82,

nothing to change inside of the integration code.

Teoretically you can create and run the script in HA terminal. In HA install visualstudiocode add-on. 

VS Code is IDE which can be use to programing in many common languages. You can create and edit files, saveing them and executing.

Better way is to create and run this script on the system where yours HA is runing. Any Linux, Unix, HassOS or so.

If you're not sure how to do it, I can make some short tutorial.

Kind regards

Jiri

**Comment by hanyzzz82** [comment]
Hi,

I have already tried to run the script in visualstudiocode but without
success.

It would be kind of you to make a short tutorial for this. I'm operating HA
on Raspberry PI.

Thanks in advance
BR Jan

pá 23. 2. 2024 v 13:16 odesílatel Jiří Horálek ***@***.***>
napsal:

**Comment by hanyzzz82** [comment]
Hi, any chance to find a little time to make a small tutorial? Thaks a lot in advance ;-)

Regards 
Jan

**Comment by hanyzzz82** [comment]
Hi there,
question - should I run the script "devices.py" only once or it should run continuously?
Thanks Jan

**Comment by jhoralek** [comment]
> Hi there, question - should I run the script "devices.py" only once or it should run continuously? Thanks Jan

Getting devices to the HA integration is running only once at the begining. 

You can run it on your own outside of the integration.

Sorry for late response, but I'm very bussy at the moment.

Kind regards

J.H.

**Comment by hanyzzz82** [comment]
Hi, OK and what should be done in the next step? Or it's enough to run the
script and then the entities should as expected?
Thx a lot
BR Jan Fiala

**Comment by hanyzzz82** [comment]
Hi there,

I've successfully retrieved list of the devices using the script, but I've no clue what to do next. Could you please give me a hint?

Thanks
BR Jan

**Comment by ds141414** [comment]
Did you download the integration in Home Assistant? 

You have to setup the integration using the URL of your connection server

**Comment by hanyzzz82** [comment]
Yes, the integration is installed in HA but the entities are in unknown
status.

**Comment by ds141414** [comment]
Hi! This happened to me as well a couple of times.  If you made changes to your config via IDM try to reload the file in connection server.  

Additionally if that does not work delete the rooms in Connection server and create the entities again.  Also remove the Inels integration and after you create the new rooms add it gain. 

This is a nuclear approach but that's how I solved it.  Still don't know why it happened 

Hope this points you in the right direction

**Comment by hanyzzz82** [comment]
Hi!

Unbelievable, it works. Indeed, I had to delete the rooms and add it again
in CS.

Thanks a lot for this advice

BR Jan

út 8. 10. 2024 v 18:43 odesílatel ds141414 ***@***.***>
napsal:

**Comment by ds141414** [comment]
Hi! 
Happy to help!
I spent a lot of time figuring that out.  However I would love to know what really happens and it breaks.

Maybe the developer can help us out 

DS

**Comment by hanyzzz82** [comment]
Hi, thanks again for this great integration. Is there any chance to add temperature sensors for the future development? I mean the ones published in connection server.
Regards
Jan

**Comment by ds141414** [comment]
Hi, The only way I found to add a temperature sensor from an Inels sensor is via a TCP sensor

  - platform: tcp
    name: water_heater_temp
    host: 192.168.1.xx
    port: 1111
    timeout: 2
    payload: "GET,0x01050009\r\n"
    value_template: "{{ value.split(',')[2] | int(base=10)/100 }}"
    unit_of_measurement: "°C"


Have a look at this [link](https://github.com/JH-Soft-Technology/InelsForHass/issues/15?notification_referrer_id=NT_kwDOA6ZOYLQxMjc1Njg1ODQzMjo2MTIzMDY4OA#issuecomment-1881535778)

Also at the attachment below from Inels.  You have to configure your CU to export the data and interface with it using telnet or the TCP sensor from home assistant 

[idm3_tutorial17_ascii-communication-protocol.pdf](https://github.com/user-attachments/files/17329853/idm3_tutorial17_ascii-communication-protocol.pdf)

**Comment by hanyzzz82** [comment]
Ok, I guess it’s not feasible for me since I’m running CU of 2nd gen.
Thanks

**Comment by ds141414** [comment]
Hi,

If your CU is this

https://www.elkoep.com/central-unit


Then it should be supported.  It is the a discontinued model but they still support it.

Also if your wall switches are from WS-40 line you should be OK

https://www.elkoep.com/4button-controller-wsb3-40

**Comment by hanyzzz82** [comment]
Hi, unfortunatelly not. It’s CU2-01M.

**Comment by ds141414** [comment]
maybe it is time for an upgrade :) 

https://www.elkoep.com/central-unit-with-2x-bus---cu3-08m

**Comment by hanyzzz82** [comment]
definitely :-)

čt 10. 10. 2024 v 19:03 odesílatel ds141414 ***@***.***>
napsal:

**Comment by JayDee8** [comment]
Does anyone faced same issue (Unexpected exception) when saving initial connection to connection server in HA? 
I'm using url of connection server, which perfectly loads login page on 8080 port. When I use port 8080 or mentioned 8001, both cause unexpected exception.

Based on log, it says:

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/inels/config_flow.py", line 75, in async_step_user
    info = await validate_input(self.hass, user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/inels/config_flow.py", line 49, in validate_input
    ping = await hass.async_add_executor_job(api.ping)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.13/site-packages/pyinels/api/__init__.py", line 79, in ping
    return self.proxy.ping()
           ~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/xmlrpc/client.py", line 1096, in __call__
    return self.__send(self.__name, args)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/xmlrpc/client.py", line 1435, in __request
    response = self.__transport.request(
        self.__host,
    ...<2 lines>...
        verbose=self.__verbose
        )
  File "/usr/local/lib/python3.13/xmlrpc/client.py", line 1140, in request
    return self.single_request(host, handler, request_body, verbose)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/xmlrpc/client.py", line 1152, in single_request
    http_conn = self.send_request(host, handler, request_body, verbose)
  File "/usr/local/lib/python3.13/xmlrpc/client.py", line 1265, in send_request
    self.send_content(connection, request_body)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/xmlrpc/client.py", line 1295, in send_content
    connection.endheaders(request_body)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/http/client.py", line 1331, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/http/client.py", line 1091, in _send_output
    self.send(msg)
    ~~~~~~~~~^^^^^
  File "/usr/local/lib/python3.13/http/client.py", line 1035, in send
    self.connect()
    ~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/http/client.py", line 1001, in connect
    self.sock = self._create_connection(
                ~~~~~~~~~~~~~~~~~~~~~~~^
        (self.host,self.port), self.timeout, self.source_address)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/socket.py", line 864, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.13/socket.py", line 849, in create_connection
    sock.connect(sa)
    ~~~~~~~~~~~~^^^^
ConnectionRefusedError: [Errno 111] Connection refused
