### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by borius973** [JH-Soft-Technology/InelsForHass#6]
Hello, I can't integrate on the connection server. Can you help me?

Log:
`Logger: custom_components.inels.config_flow
Source: custom_components/inels/config_flow.py:49
Integration: Inels ([documentation](https://github.com/JH-Soft-Technology/InelsForHass))
First occurred: 11:47:39 (5 occurrences)
Last logged: 12:06:56

Unexpected exception
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/pyinels/api/init.py", line 69, in __conn
con = ServerProxy(self.__host + ":" + str(self.__port))
File "/usr/local/lib/python3.10/xmlrpc/client.py", line 1432, in init
raise OSError("unsupported XML-RPC protocol")
OSError: unsupported XML-RPC protocol

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/config/custom_components/inels/config_flow.py", line 75, in async_step_user
info = await validate_input(self.hass, user_input)
File "/config/custom_components/inels/config_flow.py", line 49, in validate_input
ping = await hass.async_add_executor_job(api.ping)
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/usr/local/lib/python3.10/site-packages/pyinels/api/init.py", line 79, in ping
return self.proxy.ping()
File "/usr/local/lib/python3.10/site-packages/pyinels/api/init.py", line 51, in proxy
self.__proxy = self.__conn()
File "/usr/local/lib/python3.10/site-packages/pyinels/api/init.py", line 74, in __conn
raise ApiException(
pyinels.exception.ApiException: ('common_exception', 'Exception occur', OSError('unsupported XML-RPC protocol'))`

**Comment by jhoralek** [comment]
Hi @borius973 , do you use connection server as a middle part between CU unit and HA integration? It is required, because of XML-RPC protocol which is main protocol to comunicate between HA integration and CU unit of Inels.

Kind Regards

J. H.

**Comment by ds141414** [comment]
Hi,
You need to connect to the Inels Connection server.  So you need the IP address of the server, probably something like 192.168.x.x  Also you need to use the RPC port which is either 8000 or 8001.  

I hope this helps

DS

**Comment by stomko11** [comment]
@jhoralek I am trying to configure integration. I am using connection server (raspberry) and providing its IP and port. As central unit, I am using CU3-01M. However I am getting "unexpected error" message. 

```
Logger: custom_components.inels.config_flow
Source: custom_components/inels/config_flow.py:49
Integration: Inels (documentation)
First occurred: 20:12:17 (10 occurrences)
Last logged: 20:57:01

Unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pyinels/api/__init__.py", line 69, in __conn
    con = ServerProxy(self.__host + ":" + str(self.__port))
  File "/usr/local/lib/python3.10/xmlrpc/client.py", line 1432, in __init__
    raise OSError("unsupported XML-RPC protocol")
OSError: unsupported XML-RPC protocol

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/inels/config_flow.py", line 75, in async_step_user
    info = await validate_input(self.hass, user_input)
  File "/config/custom_components/inels/config_flow.py", line 49, in validate_input
    ping = await hass.async_add_executor_job(api.ping)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/pyinels/api/__init__.py", line 79, in ping
    return self.proxy.ping()
  File "/usr/local/lib/python3.10/site-packages/pyinels/api/__init__.py", line 51, in proxy
    self.__proxy = self.__conn()
  File "/usr/local/lib/python3.10/site-packages/pyinels/api/__init__.py", line 74, in __conn
    raise ApiException(
pyinels.exception.ApiException: ('common_exception', 'Exception occur', OSError('unsupported XML-RPC protocol'))
```

Any idea what could be wrong? What should I provide for central unit name.

**Comment by borius973** [comment]
@jhoralek Hello, I am using ver. connection-server-3.366 on rpi provided by Inels and central unit CU3-01M. After pressing the submit button, it throws an error. Same as @stomko11 
<img width="587" alt="Screenshot 2023-05-25 at 18 10 26" src="https://github.com/JH-Soft-Technology/InelsForHass/assets/53018702/4148ef30-6186-4153-b854-6447228a7692">

**Comment by jhoralek** [comment]
Hi there, I'm little bit busy right now.
Try port 8001 instead 8000.

Let me know.

Kind regards

**Comment by borius973** [comment]
@jhoralek Hello, same as with port 8000.

**Comment by jhoralek** [comment]
I'm running IMM server version connection-server-3.164.
Web interface is realy terrible, but you need to be sure that xmlrpc protocol is running
![image](https://github.com/JH-Soft-Technology/InelsForHass/assets/12426037/bc839eb0-2279-456d-bc2d-4342eb0f530f)

Error you provided at the begging of this issue is about (unsupported XML-RPC protocol).

Another my suggestion instead using of IP address as ServiceUrl, use HTTP prefix like ```http://IPAddress```.

And then try to use ports 8000 and 8001

**Comment by borius973** [comment]
HTTP prefix helped me, thank you!

**Comment by jhoralek** [comment]
Great, then closing.
